version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:17

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: ./target
          destination: build-artifacts

  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports

  deploy:
    executor: docker-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:bdQhUpWvsTenmxgrI/Z4u49QPvaTPhHqZk0SZpzUuQE"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Copy Docker Compose Files to Remote Server
          command: |
            scp -o StrictHostKeyChecking=no docker-compose.yml Dockerfile target/post-app.war $SSH_USER@$SSH_HOST:/home/$SSH_USER/deploy/
      - run:
          name: Deploy Application on Remote Server
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
              cd /home/$SSH_USER/deploy/
              docker-compose down
              docker-compose up -d --build
            EOF
      - run:
          name: Verify Deployment
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST curl -f http://localhost:8080/posts || exit 1

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
