version: 2.1

orbs:
    azure-acr: circleci/azure-acr@0.2.0
    docker: circleci/docker@2.1.2
    azure-aks: circleci/azure-aks@0.3.0
    azure-cli: circleci/azure-cli@1.2.2
    helm: circleci/helm@2.0.0

executors:
  posts-executor:
    environment:
      CONTAINER_IMAGE_NAME: posts/posts
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    docker:
      - image: maven:3.8.1-jdk-11
      - image: circleci/mysql

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}

      - attach_workspace:
          at: .

      # Build and test the project
      - run:
          name: Build
          command: mvn clean install

      - persist_to_workspace:
          root: .
          paths:
            - target/build

      - store_artifacts:
          path: ./target/build
  test:
    docker:
      - image: maven:3.8.1-jdk-11
      - image: circleci/mysql

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      - run:
          name: Test
          command: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}

      - store_artifacts:
          path: target/surefire-reports
      - store_test_results:
          path: target/surefire-reports

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "SHA256:bdQhUpWvsTenmxgrI/Z4u49QPvaTPhHqZk0SZpzUuQE"
      - run:
          name: Install SSH Client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      - run:
          name: SSH connection and deployment
          command: |
            scp -v -o StrictHostKeyChecking=no target/build/docker-post-app.war $SSH_USER@$SSH_HOST:/opt/tomcat/webapps/ROOT.war           
          no_output_timeout: 20m

      - run:
          name: Restart Tomcat
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST ; sudo systemctl stop tomcat ; sudo systemctl start tomcat

      - run:
          name: Verify Tomcat Deployment
          command: |
            sleep 30  # Wait for Tomcat to fully start
            curl -f http://$SSH_HOST:8080/login || exit 1

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test