version: 2.1

orbs:
    azure-acr: circleci/azure-acr@0.2.0
    docker: circleci/docker@2.1.2
    azure-aks: circleci/azure-aks@0.3.0
    azure-cli: circleci/azure-cli@1.2.2
    helm: circleci/helm@2.0.0

executors:
  posts-executor:
    environment:
      CONTAINER_IMAGE_NAME: posts/posts
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    docker:
      - image: maven:3.8.1-jdk-11
      - image: circleci/mysql

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}

      - attach_workspace:
          at: ./workspace

      - run:
          name: Print current directory
          command: pwd

      - run:
          name: Enter in src folder
          command: cd src

      - run:
          name: List src folders
          command: ls -d */

      - run:
          name: Enter in workspace folder
          command: cd ../workspace

      - run:
          name: List workspace folders
          command: ls -d */

      - persist_to_workspace:
          root: ./
          paths:
            - ./target

      - store_artifacts:
          path: ./target

      # Build and test the project
      - run:
          name: Build
          command: mvn clean install
  test:
    docker:
      - image: maven:3.8.1-jdk-11
      - image: circleci/mysql

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      - run:
          name: Test
          command: mvn test
      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/surefire-reports
      - store_test_results:
          path: target/Surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test