apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: post-app
  namespace: argocd
spec:
  project: post-app
  source:
    repoURL: 'https://github.com/manniloff/post-app.git'
    targetRevision: HEAD
    path: k8s
  destination:
    namespace: post-app   # namespace для Service/Deployment
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
