apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-app
  labels:
    app: post-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      imagePullSecrets:
        - name: acr-pull-secret   # ниже создадим этот secret
      containers:
        - name: post-app
          # PLACEHOLDER: image will be replaced by CI (see steps)
          image: slregistry.azurecr.io/post:1.0.0-20251205.074636
          ports:
            - containerPort: 1234
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/posts
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 1234
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 1234
            initialDelaySeconds: 30
            periodSeconds: 20
