apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-app
  namespace: post-app
  labels:
    app: post-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      imagePullSecrets:
        - name: acr-pull-secret   # ниже создадим этот secret
      containers:
        - name: post-app
          # PLACEHOLDER: image will be replaced by CI (see steps)
          image: .azurecr.io/myapp:eac03fc841e3c3279946159ce13b204bfc36c4e0
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 20
