apiVersion: v1
kind: Service
metadata:
  name: post-app
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app: post-app
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
